site_name: DRESSCode
site_description: Data Reduction of Extended SWIFT Sources Code
site_url: https://spacetelescope.github.io/DRESSCode/
theme:
  name: material
  favicon: img/favicon.png
  logo: img/icon.svg
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: yellow
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
  - Home: "index.md"
  - Install: "install.md"
  - Acquire Data: download_data.md
  - Usage: usage.md
  - Notes to user: notes.md
  - Contributing: developer_notes.md

repo_name: spacetelescope/DRESSCode
repo_url: https://github.com/spacetelescope/DRESSCode

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - extra
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/spacetelescope/DRESSCode"
