name: "Build docker images & run pipeline"

on:
  workflow_dispatch:
  push:

jobs:
  build_heasoft_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build HEASoft image and push to dockerhub
        run: |
          bash Docker/heasoft_image.sh
          docker push dresscodeswift/heasoft:v"$HEASOFT_VER".swift
