name: "comment-on-pr"

on:
  pull_request:

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Get a fits file
        run: |
          mkdir -p ~/dresscode-data/NGC0628/working_dir/
          wget -q 'https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HST/product/w0cx0201t_c0f.fits' -O ~/dresscode-data/NGC0628/working_dir/w0cx0201t_c0f_final_test.fits
          cp ~/dresscode-data/NGC0628/working_dir/w0cx0201t_c0f_final_test.fits ~/dresscode-data/NGC0628/working_dir/w0cx0201t_number2_c0f_final_test.fits

      - name: Create thumbnail of pipeline output
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          pip install astropy matplotlib rich
          python3 tests/fits2img.py ~/dresscode-data/NGC0628/working_dir/

        # todo: replace with our own requests.post script in order to have more control over matching imgur links / filename

      - name: publish thumbnail to imgur
        if: ${{ github.event_name == 'pull_request' }}
        uses: devicons/public-upload-to-imgur@v2.2.1
        id: publish-to-imgur
        with:
          path: "*.png"
          client_id: ${{secrets.IMGUR_CLIENT_ID}}

      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Final thumbnail images from pipeline:
            ${{ join(fromJSON(steps.publish-to-imgur.outputs.markdown_urls)) }}"
          check_for_duplicate_msg: false
          delete_prev_regex_msg: "^Final thumbnail images from pipeline: "
