name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: psf/black@stable

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # - name: Install lint dependencies
      #   run: pip install flake8 isort

      # - name: Check isort
      #   run: isort . --check --diff

      # - name: Run flake8
      #   run: flake8

      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Download artifacts (fits files) from the run's [actions page](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          check_for_duplicate_msg: false
