on:
  push:

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build --tag dresscodeswift/dresscode:latest -f Docker/dockerfile .
      - name: Run the pipeline
        run: |
          mkdir dresscode-data
          docker run --rm -t -v dresscode-data:dresscode-data dresscodeswift/dresscode /bin/bash /opt/dresscode/tests/test_pipeline.bash /opt/dresscode dresscode-data
      - name: Save pipeline output
        uses: actions/upload-artifact@v2
        with:
          name: final-fits
          path: |
            dresscode-data/NGC0628/working_dir/*final*.fits
