name: "Test Action"

on:
  # pull_request:

jobs:
  test_GH_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ls dir
        id: ls-dir
        run: |
          export OUTPUT="$(python tests/pr_comment.py '![Imgur Images](https://i.imgur.com/FbRXwrg.png),![Imgur Images](https://i.imgur.com/XdEYTIz.png),![Imgur Images](https://i.imgur.com/UO4lzz0.png),![Imgur Images](https://i.imgur.com/rZh7FOg.png),![Imgur Images](https://i.imgur.com/c5SmtXg.png),![Imgur Images](https://i.imgur.com/fLWDrAS.png)')"
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=comment_output::$(echo "$OUTPUT")"

      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "# Pipeline output (`*_final*.fits`)
            \n
            \n${{ steps.ls-dir.outputs.comment_output }}
            \n"
          check_for_duplicate_msg: false
          # delete_prev_regex_msg: '^Pipeline output \(`\*_final\*\.fits`\)'
