name: "Test Action"

on:
  pull_request:

jobs:
  test_GH_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ls dir
        id: ls-dir
        run: |
          echo "OUTPUT=$(ls)" >> $GITHUB_ENV

      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "# Pipeline output (`*_final*.fits`)
            \n
            \n${{ env.OUTPUT }}
            \n
            \n|column1|column2|
            \n|-|-|
            \n|item1a|item1b|
            \n|item2a|item2b|
            \n|item3a|item3b|
            \n"
          check_for_duplicate_msg: false
          # delete_prev_regex_msg: '^Pipeline output \(`\*_final\*\.fits`\)'
