name: "Test package"

on: [push]

jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: psf/black@stable

      - name: Install lint dependencies
        run: pip install flake8 isort

      - name: Check isort
        run: isort . --check --diff

      - name: Run flake8
        run: flake8

      - name: Pytest
        run: |
          python -m pip install -e ".[dev]"
          pytest
