name: "Test package"

# on: [push]

jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: "pip"

      - name: install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e ".[dev]"

      - uses: psf/black@stable

      - name: Check isort
        run: isort dresscode --check --diff

      - name: Run flake8
        run: flake8 dresscode

      - name: Pytest
        run: pytest
