name: "Build docker images & run pipeline"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_images_and_run_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache Raw_data
        id: cache-test-images
        uses: actions/cache@v2
        with:
          path: ~/Raw_data
          key: NGC0628-test-raw-data-${{ hashFiles('tests/download_test_data.bash') }}

      - name: Download Data
        if: steps.cache-test-images.outputs.cache-hit != 'true'
        run: |
          mkdir ~/Raw_data
          bash tests/download_test_data.bash ~/Raw_data

      - name: Build the dependency Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker build --pull --tag dresscodeswift/heasoft-caldb-wcstools:latest -f Docker/heasoft-caldb-wcstools.dockerfile .

      - name: Build the DRESSCode Docker image
        run: |
          docker build --pull --tag dresscodeswift/dresscode:latest -f Docker/dockerfile .

      - name: Run the pipeline
        run: |
          mkdir -p ~/dresscode-data/NGC0628
          cp -r ~/Raw_data ~/dresscode-data/NGC0628/Raw_data
          chmod -R a=rwx ~/dresscode-data
          docker run --user root --rm -t -v ~/dresscode-data:/data dresscodeswift/dresscode:latest /bin/bash /opt/dresscode/tests/test_pipeline.bash /data

      - name: Save pipeline output
        uses: actions/upload-artifact@v2
        with:
          name: final-fits
          path: |
            ~/dresscode-data/NGC0628/working_dir/*final*.fits

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push the dependency Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dresscodeswift/heasoft-caldb-wcstools:latest

      - name: Push the DRESSCode Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push dresscodeswift/dresscode:latest

      - name: Create thumbnail of pipeline output
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          python -m pip install astropy matplotlib
          python tests/fits2img.py ~/dresscode-data/NGC0628/working_dir/

      - name: Publish to imgur
        if: ${{ github.event_name == 'pull_request' }}
        uses: devicons/public-upload-to-imgur@v2.2.1
        id: publish-to-imgur
        with:
          path: "*.png"
          client_id: ${{secrets.IMGUR_CLIENT_ID}}

      - name: format imgur links to markdown table
        id: format-imgur-table
        # store in env. variable and escape white space characters, then set as github output
        run: |
          export OUTPUT="$(python tests/pr_comment.py '${{ join(fromJSON(steps.publish-to-imgur.outputs.markdown_urls)) }}')"
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=comment_output::$(echo "$OUTPUT")"

      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "# Pipeline output (`*_final*.fits`)
            \n
            \n${{ steps.format-imgur-table.outputs.comment_output }}
            \n
            \nDownload full fits files from the run's [actions page](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          check_for_duplicate_msg: false
          delete_prev_regex_msg: '^# Pipeline output \(`\*_final\*\.fits`\)'
