name: "Test Action"

on:
  pull_request:

jobs:
  test_GH_action:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: unsplash/comment-on-pr@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "# Pipeline output (`*_final*.fits`)

            |column1|column2|
            |-|-|
            |item1a|item1b|
            |item2a|item2b|
            |item3a|item3b|
            "
          # check_for_duplicate_msg: false
          # delete_prev_regex_msg: '^Pipeline output \(`\*_final\*\.fits`\)'
