on:
  push:

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    container:
      image: dresscodeswift/heasoft-caldb-wcstools:latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install and run pipeline
        run: |
          cd DRESSCode
          pip install -r requirements.txt
          /bin/bash /opt/dresscode/tests/test_pipeline.bash

      - name: Save pipeline output
        uses: actions/upload-artifact@v2
        with:
          name: final-fits
          path: |
            dresscode-data/NGC0628/working_dir/*final*.fits
