on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Cache Test Images
        id: cache-test-images
        uses: actions/cache@v2
        with:
          path: ~/dresscode-data/NGC0628/Raw_data/
          key: NGC0628-test-raw-data-${{ hashFiles('./tests/download_test_data.bash') }}

      - name: Download Data
        if: steps.cache-test-images.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/dresscode-data/NGC0628/Raw_data/
          bash tests/download_test_data.bash ~/dresscode-data/NGC0628/Raw_data

      - name: Build the Docker image
        run: docker build --tag dresscodeswift/dresscode:latest -f Docker/dockerfile .

      - name: Run the pipeline
        run: |
          mkdir -p ~/dresscode-data/NGC0628
          chmod -R a=rwx ~/dresscode-data
          docker run --user root --rm -t -v ~/dresscode-data:/data dresscodeswift/dresscode /bin/bash /opt/dresscode/tests/test_pipeline.bash /opt/dresscode /data

      - name: Save pipeline output
        uses: actions/upload-artifact@v2
        with:
          name: final-fits
          path: |
            ~/dresscode-data/NGC0628/working_dir/*final*.fits
